### ISSUE TITLE
La aplicación va a 'matar'  al motor de base de datos

### ISSUE THREAD

**Issue by hectorateci** [ProyectoPDSW2016/ProyectoPDSWElectroECI#2]
Esta aplicación no cierra las conexiones!
Además, no está escalando las excepciones a las capas superiores, de manera que desde la interfaz NO se puede reportar cuando hay problemas...

   public void insertEquipo(Equipo eq ,int fk_tipomodel,int fk_pres_sol){
       try{
           DaoFactory df2 = DaoFactory.getInstance(prop);
           df2.beginSession();
           df2.getDaoEquipo().insertEquipo(eq);
           <---?????           

```
   }
   catch(PersistenceException e){
       <---?????
   }
```

   }

**Comment by Manny2296** [comment]
profe me gustaria mas informacion acerca de esto, cual seria la implementacion de ese segmento de codigo para que reporte el error , la conexion deberia cerrarse justo cuando termina alguna insercion o consulta

**Comment by hectorateci** [comment]
Manuel, la idea es hacer commit y liberar la conexión al terminar cada transacción (que puede ser un conjunto de inserciones, actualizaciones, etc)... Es decir, esto se debería hacer al terminar cada operación de la capa lógica.

Si revisa la implementación del patrón dao que estamos usando, puede ver que con 'beginSession' se abre la conexión, y que con 'endSession' se hace commit y se cierra la conexión...

Revise y me cuenta...

Héctor
